name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml

  release:
    name: Release
    needs:
      - validate
    uses: ./.github/workflows/semantic-release.yaml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      id-token: write
    secrets: inherit
