name: PR

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - "golangci-default.yaml"
      - "README.md"

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml
